import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_COURSES]: [USER_ROLES.STUDENT,USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.GET_COURSE]: [USER_ROLES.STUDENT,USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.CREATE_COURSE]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.UPDATE_COURSE]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.DELETE_COURSE]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.REORDER_COURSES]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.COUNT_COURSES]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  
};
