import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_USERS]: [USER_ROLES.ADMIN],
  [CONTROLLERS.GET_USER]: [USER_ROLES.ADMIN],
  [CONTROLLERS.CREATE_USER]: [],
  [CONTROLLERS.UPDATE_USER]: [],
  [CONTROLLERS.DELETE_USER]: [USER_ROLES.ADMIN],
  [CONTROLLERS.DEACTIVATE_USER]: [],
  [CONTROLLERS.COUNT_USERS]: [USER_ROLES.ADMIN],
  [CONTROLLERS.GENERATE_EMAIL_VERIFICATION_CODE]: [USER_ROLES.ADMIN, USER_ROLES.TEACHER, USER_ROLES.STUDENT],
  [CONTROLLERS.VERIFY_EMAIL]: [USER_ROLES.ADMIN, USER_ROLES.TEACHER, USER_ROLES.STUDENT],
};
