import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_LESSONS]: [USER_ROLES.STUDENT,USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.GET_LESSON]: [USER_ROLES.STUDENT,USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.CREATE_LESSON]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.UPDATE_LESSON]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.DELETE_LESSON]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.REORDER_LESSONS]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  [CONTROLLERS.COUNT_LESSONS]: [USER_ROLES.ADMIN,USER_ROLES.TEACHER],
  
};
